package payment

import io.github.iltotore.iron.*
import io.github.iltotore.iron.constraint.collection.*

// ─── Stage 06: Scala 3 payment domain ────────────────────────────────────────
//
// Lambda-cube position: bounded λω / System Fω + type families (two axes: terms→types
// and types→types). The third axis — types depending on runtime values — is Stage 7.
//
// Key additions over the Java typestate stage:
//
//   - Risk phantom types (LowRisk, MediumRisk, HighRisk as sealed traits):
//     The risk level is now a compile-time type token, not a runtime String.
//     Every site that uses risk evidence gets exhaustiveness checking from the
//     compiler. Adding a new risk level forces every match to handle it.
//
//   - Approval[R <: Risk] indexed by the phantom risk type:
//     Improvement: `AutoApproved : Approval[LowRisk]` cannot satisfy
//     `Approval[MediumRisk]`. Bob's bug — calling auto-approve on a medium-risk
//     order — is an unrepresentable program. The approval constructor IS the
//     evidence; skipping it is a type error, not a runtime surprise.
//     (Note: `+R` covariance means Approval appears only in output position —
//     it produces evidence, never consumes R. Covariance is sound but not
//     load-bearing; the safety comes from authorize[R]'s type inference.)
//
//   - Refined type: NonEmptyString = String :| MinLength[1]
//     The predicate `length >= 1` lives in the type itself — not just checked at
//     construction time but carried as part of the type. Plain `String` does not
//     satisfy `NonEmptyString`; the literal `""` is rejected at compile time.
//     Used for order and customer identifiers, where an empty string slipping
//     through a boundary would silently group records under a single key.
//
//   - Opaque + refined nominal IDs: OrderId, CustomerId
//     Refinement (non-empty) is layered on top of opacity (nominal distinctness).
//     OrderId and CustomerId are NonEmptyStrings underneath, but the compiler
//     treats them as distinct types — an OrderId cannot stand in for a CustomerId.
//
//   - Opaque nominal IDs: AuthCode, CaptureId, RefundId
//     Internally generated by lifecycle transitions; opacity prevents an auth
//     code being mistakenly used as a capture id (or vice versa) anywhere in
//     downstream code. Zero runtime cost.
//
//   - Typestate via separate types (AuthorizedPayment[R], CapturedPayment, …):
//     Not just separate class names (Stage 4 had that). AuthorizedPayment[R]
//     carries the risk parameter R through the lifecycle. Downstream operations
//     (capture, refund) inherit the risk evidence. The state is indexed, not
//     merely named.
//
//   - RefundMechanism replaces supportsRefund: Boolean:
//     Refund availability is about settlement process, not risk level.
//     Card/Wallet → InstantReversal; Invoice → CreditNoteRequired.
//     The sealed type forces every refund call site to handle both cases.
//
// Ceiling that remains (what Idris 2 removes):
//   - The protocol selected for a session is chosen at runtime from a fixed menu.
//   - Computing a protocol TYPE from a runtime risk value requires dependent types.

// ─── Risk phantom types ───────────────────────────────────────────────────────

sealed trait Risk
sealed trait LowRisk    extends Risk
sealed trait MediumRisk extends Risk
sealed trait HighRisk   extends Risk

// ─── Approval — evidence indexed by risk level ────────────────────────────────
//
// Approval[LowRisk]    can only be constructed as AutoApproved.
// Approval[MediumRisk] requires a ThreeDSProof.
// Approval[HighRisk]   requires a ManualReviewApproval.
//
// authorize() is parameterized by R: it requires an Approval[R].
// The compiler ensures you cannot pass AutoApproved to a high-risk authorization.

sealed trait Approval[+R <: Risk]
// +R (covariant): Approval only appears in output position — it produces evidence,
// never consumes R. Covariance allows Approval[LowRisk] to be stored in an
// Approval[Risk] collection. The safety guarantee comes from authorize[R <: Risk]
// inferring R from the argument, not from variance restrictions.

case object AutoApproved extends Approval[LowRisk]

final case class ThreeDSProof(challengeId: String, liabilityShift: Boolean)
final case class ThreeDSApproved(proof: ThreeDSProof) extends Approval[MediumRisk]

final case class ManualReviewApproval(reviewer: String, note: String)
final case class ReviewerApproved(approval: ManualReviewApproval) extends Approval[HighRisk]

// ─── Refined value type ───────────────────────────────────────────────────────
//
// NonEmptyString is a REFINED type: the predicate `MinLength[1]` is part of
// the type itself, not just enforced at construction time.
// `String :| MinLength[1]` is `IronType[String, MinLength[1]]` — an opaque
// type carrying the constraint. The compiler distinguishes it from plain String,
// and a literal `""` is rejected at compile time.

type NonEmptyString = String :| MinLength[1]
extension (s: NonEmptyString) inline def value: String = s.asInstanceOf[String]

// ─── Opaque + refined nominal ID types ───────────────────────────────────────
//
// OrderId and CustomerId carry two compile-time guarantees:
//   1. Refinement: the underlying String is non-empty.
//   2. Opacity:   OrderId and CustomerId are nominally distinct from each other
//                 and from any other String, even though both reduce to a
//                 String at runtime. Zero boxing cost.
//
// A literal `""` cannot be lifted into either via `refineEither`; an OrderId
// cannot stand in for a CustomerId in any signature.

opaque type OrderId    = NonEmptyString
opaque type CustomerId = NonEmptyString

object OrderId:
  def of(s: String): Either[String, OrderId] =
    s.refineEither[MinLength[1]].left.map(_ => s"orderId must be non-empty")
  inline def unsafe(s: NonEmptyString): OrderId = s

object CustomerId:
  def of(s: String): Either[String, CustomerId] =
    s.refineEither[MinLength[1]].left.map(_ => s"customerId must be non-empty")
  inline def unsafe(s: NonEmptyString): CustomerId = s

extension (id: OrderId)    def orderIdStr:    String = id.asInstanceOf[String]
extension (id: CustomerId) def customerIdStr: String = id.asInstanceOf[String]

// ─── Opaque lifecycle ID types ────────────────────────────────────────────────
//
// AuthCode, CaptureId, and RefundId are generated by the lifecycle transitions
// themselves and are never empty by construction — they do not need refinement.
// What they DO need is opacity: an authorization code must not be usable where
// a capture id is expected, even though both are String underneath.

opaque type AuthCode  = String
opaque type CaptureId = String
opaque type RefundId  = String

object AuthCode:
  def of(s: String): AuthCode = s

object CaptureId:
  def of(s: String): CaptureId = s

object RefundId:
  def of(s: String): RefundId = s

extension (c: AuthCode)  def authCodeStr: String  = c
extension (c: CaptureId) def captureIdStr: String = c
extension (r: RefundId)  def refundIdStr: String  = r

// ─── Refund mechanism — settlement process, not risk level ───────────────────
//
// Refund availability is determined by payment METHOD, not risk level.
// Card and Wallet support instant payment reversal.
// Invoice uses credit-note accounting — a different settlement process.
// The sealed type forces every refund call site to handle both cases explicitly.

sealed trait RefundMechanism
object RefundMechanism:
  case object InstantReversal    extends RefundMechanism
  case object CreditNoteRequired extends RefundMechanism

// ─── Domain types ─────────────────────────────────────────────────────────────

sealed trait PaymentMethod:
  def refundMechanism: RefundMechanism = this match
    case PaymentMethod.Invoice(_) => RefundMechanism.CreditNoteRequired
    case _                        => RefundMechanism.InstantReversal
  def label: String = this match
    case PaymentMethod.Card(t)    => s"card($t)"
    case PaymentMethod.Wallet(t)  => s"wallet($t)"
    case PaymentMethod.Invoice(r) => s"invoice($r)"

object PaymentMethod:
  final case class Card(token: String)        extends PaymentMethod
  final case class Wallet(token: String)      extends PaymentMethod
  final case class Invoice(reference: String) extends PaymentMethod

// OrderLine: quantity is plain Int. A line with quantity 0 is permitted
// (free promotional items, discount lines). The domain invariant we DO carry
// in the type lives in the order header below — non-empty identifiers.
final case class OrderLine(sku: String, unitPriceCents: Int, quantity: Int):
  def totalCents: Int = unitPriceCents * quantity

object OrderLine:
  def of(sku: String, unitPriceCents: Int, quantity: Int): OrderLine =
    OrderLine(sku, unitPriceCents, quantity)

final case class Order private (
  orderId:       OrderId,
  customerId:    CustomerId,
  lines:         List[OrderLine],
  paymentMethod: PaymentMethod,
):
  def totalCents: Int = lines.map(_.totalCents).sum

object Order:
  def of(
    orderId: String, customerId: String,
    lines: List[OrderLine], paymentMethod: PaymentMethod,
  ): Either[String, Order] =
    for
      oid <- OrderId.of(orderId)
      cid <- CustomerId.of(customerId)
      _   <- Either.cond(lines.nonEmpty, (), "Order must have at least one line")
    yield Order(oid, cid, lines, paymentMethod)

// ─── Risk assessment ──────────────────────────────────────────────────────────

final case class RiskSnapshot(
  level:                String,
  requires3DS:          Boolean,
  requiresManualReview: Boolean,
  refundPermitted:      Boolean,
  captureWindowHours:   Int,
):
  override def toString: String =
    s"RiskSnapshot(level=$level, 3ds=$requires3DS, manual=$requiresManualReview, refund=$refundPermitted, window=${captureWindowHours}h)"

final case class ThreeDSChallenge(challengeId: String, amountBand: String):
  override def toString: String = s"ThreeDSChallenge($challengeId, band=$amountBand)"

final case class ManualReviewRequest(queue: String, reason: String):
  override def toString: String = s"ManualReviewRequest(queue=$queue, reason=$reason)"

// ─── Typestate payment objects ────────────────────────────────────────────────
//
// Separate types (not just phantom parameters) for each lifecycle stage.
// The opaque nominal IDs prevent mixing up authCode with captureId at compile time.

final case class AuthorizedPayment[R <: Risk](
  order:      Order,
  authCode:   AuthCode,
  approval:   Approval[R],
  auditTrail: List[String],
):
  override def toString: String =
    s"AuthorizedPayment(order=${order.orderId.orderIdStr}, auth=${authCode.authCodeStr}, trail=$auditTrail)"

final case class CapturedPayment(
  order:      Order,
  captureId:  CaptureId,
  auditTrail: List[String],
):
  override def toString: String =
    s"CapturedPayment(order=${order.orderId.orderIdStr}, cap=${captureId.captureIdStr}, trail=$auditTrail)"

final case class RefundedPayment(
  order:      Order,
  refundId:   RefundId,
  auditTrail: List[String],
):
  override def toString: String =
    s"RefundedPayment(order=${order.orderId.orderIdStr}, refund=${refundId.refundIdStr}, trail=$auditTrail)"

// ─── Typed lifecycle transitions ──────────────────────────────────────────────

def authorize[R <: Risk](order: Order, approval: Approval[R]): AuthorizedPayment[R] =
  val note = approval match
    case AutoApproved        => "auto-approved"
    case ThreeDSApproved(p)  => s"3ds:${p.challengeId} shift=${p.liabilityShift}"
    case ReviewerApproved(a) => s"manual-review:${a.reviewer}"
  AuthorizedPayment(
    order      = order,
    authCode   = AuthCode.of(s"auth-${order.orderId.orderIdStr}"),
    approval   = approval,
    auditTrail = List(s"initiated:${order.orderId.orderIdStr}", s"authorized:$note"),
  )

def capture(auth: AuthorizedPayment[?]): CapturedPayment =
  CapturedPayment(
    order      = auth.order,
    captureId  = CaptureId.of(s"cap-${auth.order.orderId.orderIdStr}"),
    auditTrail = auth.auditTrail :+ s"captured:${auth.order.totalCents}c",
  )

def refund(cap: CapturedPayment): Either[String, RefundedPayment] =
  cap.order.paymentMethod.refundMechanism match
    case RefundMechanism.CreditNoteRequired =>
      Left(s"${cap.order.paymentMethod.label}: credit note required — instant reversal not available")
    case RefundMechanism.InstantReversal =>
      Right(RefundedPayment(
        order      = cap.order,
        refundId   = RefundId.of(s"refund-${cap.order.orderId.orderIdStr}"),
        auditTrail = cap.auditTrail :+ s"refunded:${cap.order.totalCents}c",
      ))
