// Clock: 0:00–0:30
#import "../theme.typ": *
#import "../components.typ": *

// The QR is regenerated by tools/make-qr.py, which is the only place the URL
// is written down. Error level Q so it survives a projector.
#title-slide(
  qr: qr-plate([slides, and the code \
    for all six stages]),
  [Type-Driven Programming],
  [Correctness by Construction from the Basics to the Cutting Edge],
  [
    Java Meetup · Inspired Consulting, Köln · 20 Aug 2026 \
    #text(fill: pal.fg-dark-faint)[github.com/mbauer83/type-driven-programming-talk-2026]
  ],
  [Michael Bauer],
)

#speaker-note[
#read("../scripts/01-title.md")
]
